name: TreeOrdination

dependencies:
    - python >=3.11
    - pip
    - pip:
        - LANDMarkClassifier >= 2.1.0
        - numpy >= 2.1.3
        - scikit-learn >= 1.6.1
        - umap-learn >= 0.5.7
        - shap >= 0.47.1
        - seaborn
